<?php
session_start();

require_once "../connection.php";


if (!isset($_SESSION['id'])) {
    header('Location: ' . "/admin/login.phtml", true, 302);
    exit();
}

$pdo = Database::getConnection();

if (isset($_POST['1'])) {
    foreach ($_POST as $id => $text) {
        $stmt = $pdo->prepare("UPDATE textareas SET text = ? WHERE id = ?");
        $stmt->execute([$text, $id]);
    }
}

$stmt = $pdo->prepare("SELECT * FROM textareas");
$stmt->execute();
$textAreas = $stmt->fetchAll(\PDO::FETCH_ASSOC);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Login</title>
</head>
<body>
<div class="container">
    <form action="" method="post">
        <?php foreach ($textAreas as $t) { ?>
            <div class="form-group">
                <label for="<?= $t['id'] ?>"></label>
                <textarea name="<?= $t['id'] ?>" class="form-control" id="<?= $t['id'] ?>"><?= $t['text'] ?></textarea>
            </div>
        <?php } ?>
        <div class="form-group mt-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
</body>
</html>