<?php
session_start();

require_once "../connection.php";

$error = "";
if (isset($_POST['login'])) {
    $pdo = getConnection();
    $stmt = $pdo->prepare("SELECT id FROM users WHERE login=? AND password=? LIMIT 1");
    $stmt->execute([$_POST['login'], sha1($_POST['password'])]);
    $user = $stmt->fetch();
    if ($user !== false) {
        $_SESSION["id"] = $user["id"];
        header('Location: ' . "/admin", true, 302);

        exit();
    }


    $error = "<pre class='text-danger'>Credentials are incorrect</pre>";
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Login</title>
</head>
<body>
<div class="container mt-3">
    <form action="" method="post">
        <?= $error ?>
        <div class="form-group">
            <label for="login">Login</label>
            <input name="login" class="form-control" id="login" placeholder="Login">
        </div>
        <div class="form-group mt-3">
            <label for="password">Password</label>
            <input name="password" type="password" class="form-control" id="password" placeholder="Password">
        </div>
        <div class="form-group mt-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
</body>
</html>